name: Build Windows EXE
on:
  push:
    paths:
      - 'script.py'
      - 'icon.ico'
      - 'version.rc'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify files exist
        run: |
          if (-not (Test-Path "script.py")) { throw "script.py not found" }
          if (-not (Test-Path "icon.ico")) { throw "icon.ico not found" }
          if (-not (Test-Path "version.rc")) { throw "version.rc not found" }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pynput pyarmor

      - name: Obfuscate code
        run: |
          pyarmor gen --output ./build script.py

      - name: Compile with Nuitka
        run: |
          python -m nuitka --onefile `
                 --windows-disable-console `
                 --remove-output `
                 --windows-icon-from-ico=icon.ico `
                 --windows-version-file=version.rc `
                 --output-filename="KeyboardManager.exe" `
                 --include-package=pynput `
                 ./build/script.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KeyboardManager
          path: KeyboardManager.exe
          retention-days: 3
