name: Build Windows EXE
on:
  push:
    paths:
      - 'script.py'
      - 'icon.ico'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify files exist
        run: |
          if (-not (Test-Path "script.py")) { throw "script.py not found" }
          if (-not (Test-Path "icon.ico")) { throw "icon.ico not found" }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests pyarmor pynput crypto scapy psutil

      - name: Install UPX
        run: |
          choco install upx -y

      - name: Obfuscate code
        run: |
          pyarmor gen --output ./dist script.py

      - name: Compile with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --noconsole `
                     --icon "icon.ico" `
                     --name "virus.exe" `
                     --add-data "icon.ico;." `
                     --hidden-import "pynput" `
                     --upx-dir="C:\upx" `
                     ./dist/script.py

      - name: Make binary more suspicious
        run: |
          # Add junk sections
          echo "Adding suspicious PE sections..."
          curl -L -o pefile.py https://raw.githubusercontent.com/erocarrera/pefile/master/pefile.py
          python -c "
          import pefile
          pe = pefile.PE('dist/virus.exe')
          pe.sections[-1].Name = b'.malz'
          pe.sections[-1].Characteristics = 0xE0000020
          pe.write('dist/virus_modified.exe')
          "
          mv dist/virus_modified.exe dist/virus.exe -Force
      
      - name: Add entropy (packer simulation)
        run: |
          # Append random data to increase entropy
          python -c "import os; open('dist/virus.exe','ab').write(os.urandom(1024*100))"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cute_AV_Trigger
          path: dist/virus.exe
          retention-days: 1
