name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PyInstaller and Pillow
        run: pip install pyinstaller pillow
      - name: Build EXE with icon
        run: pyinstaller --onefile --icon=kernel-icon.png kernel32.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: PY2EXE1234
          path: dist/
